name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  ci:
    name: Tests & Analyse statique
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ina_zaoui_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      APP_ENV: test
      APP_SECRET: ci-secret-for-tests
      DATABASE_URL: "postgresql://postgres:postgres@127.0.0.1:5432/ina_zaoui?serverVersion=16&charset=utf8"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: ctype, iconv, mbstring, intl, pdo_pgsql
          coverage: none

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: PHP-CS-Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --diff

      - name: PHPStan
        run: vendor/bin/phpstan analyse --no-progress

      - name: Create schema
        run: php bin/console doctrine:schema:create

      - name: Init migrations metadata storage
        run: php bin/console doctrine:migrations:sync-metadata-storage

      - name: Mark migrations as executed
        run: php bin/console doctrine:migrations:version --add --all --no-interaction

      - name: Load fixtures
        run: php bin/console doctrine:fixtures:load --no-interaction --purge-with-truncate

      - name: PHPUnit
        run: vendor/bin/phpunit
